TestePraticoDev/Models/ItemPedido.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace TestePraticoDev.Models
{
    public class ItemPedido
    {
        public int Id { get; set; }
        [ForeignKey("Parent")]
        public int PedidoId { get; set; }
        public string NomeProduto { get; set; }
        public int Quantidade { get; set; } //produto
        public decimal Valor { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}

TestePraticoDev/Models/Pedido.cs
using System;
using System.Collections.Generic;

namespace TestePraticoDev.Models
{
    public class Pedido
    {
        public int Id { get; set; }
        public string NomeCliente { get; set; }
        public DateTime Data { get; set; }
        public decimal ValorTotal { get; set; }
        public virtual ICollection<ItemPedido> ItensPedido { get; set; }
    }
}

TestePraticoDev/ViewModels/PedidoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TestePraticoDev.ViewModels
{
    public class PedidoViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O nome do cliente é obrigatório.")]
        [StringLength(100)]
        [MinLength(2, ErrorMessage = "O nome do cliente deve ter no mínimo 2 caracteres.")]
        public string? NomeCliente { get; set; }

        [Required(ErrorMessage = "A data do pedido é obrigatória.")]
        [DataType(DataType.Date, ErrorMessage = "Formato de data inválido.")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Data { get; set; }

        [Required(ErrorMessage = "O valor é obrigatório.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "O valor deve ser maior que zero.")]
        public decimal ValorTotal { get; set; }
        public int QuantidadeItens { get; set; }

        public List<ItemPedidoViewModel>? ItensPedido { get; set; }
    }

    public class ItemPedidoViewModel 
    {
        public int Id { get; set; }
        public int PedidoId { get; set; }
        public string? NomeProduto { get; set; }
        public int Quantidade { get; set; }
        public decimal Valor { get; set; } //preço produto
    }
}

TestePraticoDev/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using TestePraticoDev.Context;
using TestePraticoDev.Services.Interfaces;
using TestePraticoDev.ViewModels;

namespace TestePraticoDev.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IPedidoService _pedidoService;

        public PedidoController(AppDbContext context, IPedidoService pedidoService)
        {
            _pedidoService = pedidoService;
        }

        //GET /api/pedidos
        //Retorna a lista de todos os pedidos.
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _pedidoService.GetAll());
        }

        //GET /api/pedidos/{id} 
        //Retorna os detalhes de um pedido específico, incluindo os itens do pedido.
        [HttpGet]
        public async Task<IActionResult> Detalhes(int id)
        {
            var pedido = await _pedidoService.GetPedidoById(id);
            pedido.ItensPedido = await _pedidoService.GetItensPedidoById(id);
            return View(pedido);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var pedido = new PedidoViewModel();
            pedido.Data = DateTime.Now;
            return View(pedido);
        }

        //POST /api/pedidos - Adiciona um novo pedido.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PedidoViewModel pedido)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(pedido);
                }

                await _pedidoService.Insert(pedido);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var pedido = await _pedidoService.GetPedidoById(id);
            pedido.ItensPedido = await _pedidoService.GetItensPedidoById(id);
            return View(pedido);
        }

        //PUT /api/pedidos/{id} 
        //Atualiza um pedido existente. (Decidi manter em POST pois faz mais sentido de acordo com o MVC)

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PedidoViewModel pedido)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(pedido);
                }

                await _pedidoService.Update(pedido);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View(await _pedidoService.GetPedidoById(id));
        }

        //DELETE /api/pedidos/{id} - Remove um pedido
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(PedidoViewModel pedido)
        {
            try
            {
                await _pedidoService.Delete(pedido);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

TestePraticoDev/Views/Pedido/Create.cshtml
@model TestePraticoDev.ViewModels.PedidoViewModel

@{
    Layout = "_Layout";
}

<head>

    <title>
        Criar Pedido
    </title>

</head>

<body>
    <div>
        <h3> Criar um novo Pedido </h3>
    </div>

    @using (Html.BeginForm("Create", "Pedido", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                @Html.LabelFor(model => model.NomeCliente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NomeCliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomeCliente, "", new { @class = "text-danger" })
                </div>
            </div>
            <br>
            <div class="form-group row">
                @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control", @placeholder = "dd/MM/yyyy", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
                </div>
            </div>
            <br>
            <div class="form-group row">
                @Html.LabelFor(model => model.ValorTotal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ValorTotal, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.ValorTotal, "", new { @class = "text-danger" })
                </div>
            </div>
            <br>
            <div class="form-group row">
                @Html.LabelFor(model => model.QuantidadeItens, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-default" onclick="decrementarQuantidade()">-</button>
                        </span>
                        @Html.EditorFor(model => model.QuantidadeItens, new { htmlAttributes = new { @class = "form-control text-center", @readonly = "readonly" } })
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-default" onclick="incrementarQuantidade()">+</button>
                        </span>
                    </div>
                    @Html.ValidationMessageFor(model => model.QuantidadeItens, "", new { @class = "text-danger" })
                </div>
            </div>
            <br>
            <div class="form-group row">
                <div class="col-md-offset-2 col-md-2" style="margin-left: 1200px">
                    <button type="submit" onclick="location.href='@Url.Action("Create", "Pedido")'" class="btn btn-success"> Salvar </button>
                </div>
                <div class="col-md-offset-2 col-md-2">
                    @Html.ActionLink("Voltar a página principal", "Index")
                </div>
            </div>
        </div>
    }
</body>

@*<script>
    // Funções para incrementar e decrementar a quantidade
    function incrementarQuantidade() {
        var quantidade = parseInt($('#QuantidadeItens').val());
        $('#QuantidadeItens').val(quantidade + 1);
        console.log($('#ValorTotal').val())
        var valorPorItem = 500;
        var valorAtual = $('#ValorTotal').val();
        if (quantidade > 0) {
            $('#ValorTotal').val(valorAtual + valorPorItem);
        }

    }

    function decrementarQuantidade() {
        var quantidade = parseInt($('#QuantidadeItens').val());
        if (quantidade > 1) {
            $('#QuantidadeItens').val(quantidade - 1);

        }
    }


</script>*@

<script>
    // Função para incrementar a quantidade e atualizar o ValorTotal
    function incrementarQuantidade() {
        var quantidade = parseInt($('#QuantidadeItens').val());
        var valorPorItem = 500;
        $('#QuantidadeItens').val(quantidade + 1);
        var novoValorTotal = (quantidade + 1) * valorPorItem;
        $('#ValorTotal').val(formatarValor(novoValorTotal)); // Define 2 casas decimais para o valor
    }

    // Função para decrementar a quantidade e atualizar o ValorTotal
    function decrementarQuantidade() {
        var quantidade = parseInt($('#QuantidadeItens').val());
        if (quantidade > 1) {
            var valorPorItem = 500;
            $('#QuantidadeItens').val(quantidade - 1);
            var novoValorTotal = (quantidade - 1) * valorPorItem;
            $('#ValorTotal').val(formatarValor(novoValorTotal)); // Define 2 casas decimais para o valor
        }
    }

    function formatarValor(valor) {
        var valorFormatado = valor.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
        return valorFormatado;
    }
</script>

TestePraticoDev/Views/Pedido/Delete.cshtml
@using Microsoft.AspNetCore.Routing
@model TestePraticoDev.ViewModels.PedidoViewModel

@{
    Layout = "_Layout";
}

<head>

    <title>
        Exclusão
    </title>

</head>

<body>
    <div>
        <h3> Excluir Pedido </h3>
    </div>

    @using (Html.BeginForm("Delete", "Pedido", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.Id)
        @Html.AntiForgeryToken()

        <fieldset disabled>
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    @Html.LabelFor(model => model.NomeCliente, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NomeCliente, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.NomeCliente, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control", @placeholder = "dd/MM/yyyy", disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>
                <div class="form-group row">
                    @Html.LabelFor(model => model.ValorTotal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ValorTotal, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.ValorTotal, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </fieldset>
        <br>
        <div>
            <div class="form-group row">
                <div class="col-md-offset-2 col-md-6" style="margin-left: 1200px">
                    <button type="submit" onclick="location.href='@Url.ActionLink("Home", "Index")'" class="btn btn-outline-danger"> Confirmar Exclusão </button>
                </div>
                <div class="col-md-offset-2 col-md-6">
                    @Html.ActionLink("Voltar a página principal", "Index")
                </div>
            </div>
        </div>

    }
</body>

TestePraticoDev/Views/Pedido/Detalhes.cshtml
@model TestePraticoDev.ViewModels.PedidoViewModel

@{
    Layout = "_Layout";
    ViewBag.Title = "Detalhes do Pedido";
}

<div>
    <h2>Detalhes do Pedido</h2>
</div>

<div>
    <h4>ID Pedido - @Model.Id</h4>
    <h4>Cliente - @Model.NomeCliente</h4>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Nome do Produto</th>
            <th>Quantidade</th>
            <th>Valor Unitário</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ItensPedido)
        {
            <tr>
                <td>@item.NomeProduto</td>
                <td>@item.Quantidade</td>
                <td>@item.Valor.ToString("C")</td>
            </tr>
        }
    </tbody>
</table>

<div>
    @Html.ActionLink("Voltar à Lista de Pedidos", "Index")
</div>

TestePraticoDev/Views/Pedido/Edit.cshtml
@model TestePraticoDev.ViewModels.PedidoViewModel

@{
    Layout = "_Layout";
}

<head>

    <title>
        Alteração
    </title>

</head>

<body>
    <div>
        <h3> Alterar Pedido </h3>
    </div>


    @using (Html.BeginForm("Edit", "Pedido", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.Id)

        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                @Html.LabelFor(model => model.NomeCliente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NomeCliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomeCliente, "", new { @class = "text-danger" })
                </div>
            </div>
            <br>
            <div class="form-group row">
                @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control", @placeholder = "dd/MM/yyyy", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
                </div>
            </div>
            <br>
            <div class="form-group row">
                @Html.LabelFor(model => model.ValorTotal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ValorTotal, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.ValorTotal, "", new { @class = "text-danger" })
                </div>
            </div>
            <br>
            <br>
            <div class="form-group row">
                <div class="col-md-offset-2 col-md-10" style="margin-left:1200px;">
                    <button type="submit" onclick="location.href='@Url.Action("Update", "Pedido")'" class="btn btn-primary"> Confirmar </button>
                </div>
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Voltar a página principal", "Index")
                </div>
            </div>
        </div>
    }
</body>

TestePraticoDev/Views/Pedido/Index.cshtml
@using Microsoft.AspNetCore.Routing
@model List<TestePraticoDev.ViewModels.PedidoViewModel>

@{
    Layout = "_Layout";
}

<head>
    <title>
        Criação de Pedido
    </title>
</head>

<body>
    <div>
        <h3> Pedidos </h3>
    </div>

    <div>
        <button type="submit" onclick="location.href='@Url.Action("Create", "Pedido")'" class="btn btn-primary"> Criar novo Pedido </button>
    </div>

    <table class="table">
        <tr>
            <th>Código</th>
            <th>Nome do Cliente</th>
            <th>Data de criação</th>
            <th>Valor</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var pedido in Model)
        {
            <tr>
                <td>@Html.DisplayFor(model => pedido.Id)</td>
                <td>@Html.DisplayFor(model => pedido.NomeCliente)</td>
                <td>@Html.DisplayFor(model => pedido.Data)</td>
                <td>@Html.DisplayFor(model => pedido.ValorTotal)</td>

                <td>
                    <button type="submit" onclick="location.href='@Url.Action("Detalhes", "Pedido",
                    new RouteValueDictionary(new { id = pedido.Id }))'" class="btn btn-info">
                        Detalhes
                    </button>
                </td>
                <td>
                    <button type="submit" onclick="location.href='@Url.Action("Edit", "Pedido",
                    new RouteValueDictionary(new { id = pedido.Id }))'" class="btn btn-primary">
                        Editar
                    </button>
                </td>
                <td>
                    <button type="submit" onclick="location.href='@Url.Action("Delete", "Pedido",
                    new RouteValueDictionary(new { id = pedido.Id }))'" class="btn btn-danger">
                        Excluir
                    </button>
                </td>
            </tr>
        }
    </table>
</body>

TestePraticoDev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="~/lib/bootstrap/" rel="stylesheet">
    <link href="~/lib/bootstrap/Content/bootstrap.css" rel="stylesheet">
    <link href="~/lib/bootstrap/Content/Site.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="margin-top: 50px" >
        <div class="container">
            <div class="navbar-header">
              
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Teste Prático Agência Darwin </p>
        </footer>
    </div>

</body>
</html>